
meta_product_name: "Dejavu"
meta_title: "Dejavu - Remember what you want to experience"
meta_description: "A map-forward website that allows you to share and find experiences.
  See the world through your friends' eyes/"
meta_image: "homepage_1.png" # should exist in `app/assets/images/`
